# Autogenerated using ProtoBuf.jl v1.3.0
# original file: Command.proto (proto3 syntax)

module Command_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export CmdCancelOID, CmdCfgOverride, CmdFetchTargetPortfolio


struct CmdCancelOID
    oid::Int32
end
PB.default_values(::Type{CmdCancelOID}) = (;oid = zero(Int32))
PB.field_numbers(::Type{CmdCancelOID}) = (;oid = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CmdCancelOID}, _endpos::Int=0, _group::Bool=false)
    oid = zero(Int32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            oid = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return CmdCancelOID(oid)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CmdCancelOID)
    initpos = position(e.io)
    x.oid != zero(Int32) && PB.encode(e, 1, x.oid)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CmdCancelOID)
    encoded_size = 0
    x.oid != zero(Int32) && (encoded_size += PB._encoded_size(x.oid, 1))
    return encoded_size
end

struct CmdCfgOverride
    cfg_name::String
    key::String
    value::String
end
PB.default_values(::Type{CmdCfgOverride}) = (;cfg_name = "", key = "", value = "")
PB.field_numbers(::Type{CmdCfgOverride}) = (;cfg_name = 1, key = 2, value = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CmdCfgOverride}, _endpos::Int=0, _group::Bool=false)
    cfg_name = ""
    key = ""
    value = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            cfg_name = PB.decode(d, String)
        elseif field_number == 2
            key = PB.decode(d, String)
        elseif field_number == 3
            value = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return CmdCfgOverride(cfg_name, key, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CmdCfgOverride)
    initpos = position(e.io)
    !isempty(x.cfg_name) && PB.encode(e, 1, x.cfg_name)
    !isempty(x.key) && PB.encode(e, 2, x.key)
    !isempty(x.value) && PB.encode(e, 3, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CmdCfgOverride)
    encoded_size = 0
    !isempty(x.cfg_name) && (encoded_size += PB._encoded_size(x.cfg_name, 1))
    !isempty(x.key) && (encoded_size += PB._encoded_size(x.key, 2))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 3))
    return encoded_size
end

struct CmdFetchTargetPortfolio
    symbol::String
end
PB.default_values(::Type{CmdFetchTargetPortfolio}) = (;symbol = "")
PB.field_numbers(::Type{CmdFetchTargetPortfolio}) = (;symbol = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CmdFetchTargetPortfolio}, _endpos::Int=0, _group::Bool=false)
    symbol = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            symbol = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return CmdFetchTargetPortfolio(symbol)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CmdFetchTargetPortfolio)
    initpos = position(e.io)
    !isempty(x.symbol) && PB.encode(e, 1, x.symbol)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CmdFetchTargetPortfolio)
    encoded_size = 0
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 1))
    return encoded_size
end
end # module
