# Autogenerated using ProtoBuf.jl v1.3.0
# original file: Common.proto (proto3 syntax)

module Common_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export SecurityTypePb, VectorDoublePb, OptionQuotePb, OptionRightPb, HoldingPb, TradePb
export QuotePb, MarketDataSnapByUnderlyingPb, TradesPb, QuotesPb, MarketDataHistoryPb


@enumx SecurityTypePb EQUITY=0 OPTION=1

struct VectorDoublePb
    values::Vector{Float64}
end
PB.default_values(::Type{VectorDoublePb}) = (;values = Vector{Float64}())
PB.field_numbers(::Type{VectorDoublePb}) = (;values = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VectorDoublePb}, _endpos::Int=0, _group::Bool=false)
    values = PB.BufferedVector{Float64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, values)
        else
            Base.skip(d, wire_type)
        end
    end
    return VectorDoublePb(values[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VectorDoublePb)
    initpos = position(e.io)
    !isempty(x.values) && PB.encode(e, 1, x.values)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VectorDoublePb)
    encoded_size = 0
    !isempty(x.values) && (encoded_size += PB._encoded_size(x.values, 1))
    return encoded_size
end

struct OptionQuotePb
    bid::Float32
    ask::Float32
end
PB.default_values(::Type{OptionQuotePb}) = (;bid = zero(Float32), ask = zero(Float32))
PB.field_numbers(::Type{OptionQuotePb}) = (;bid = 1, ask = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OptionQuotePb}, _endpos::Int=0, _group::Bool=false)
    bid = zero(Float32)
    ask = zero(Float32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            bid = PB.decode(d, Float32)
        elseif field_number == 2
            ask = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return OptionQuotePb(bid, ask)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OptionQuotePb)
    initpos = position(e.io)
    x.bid !== zero(Float32) && PB.encode(e, 1, x.bid)
    x.ask !== zero(Float32) && PB.encode(e, 2, x.ask)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OptionQuotePb)
    encoded_size = 0
    x.bid !== zero(Float32) && (encoded_size += PB._encoded_size(x.bid, 1))
    x.ask !== zero(Float32) && (encoded_size += PB._encoded_size(x.ask, 2))
    return encoded_size
end

@enumx OptionRightPb CALL=0 PUT=1

struct HoldingPb
    symbol::String
    quantity::Float32
    security_type::SecurityTypePb.T
end
PB.default_values(::Type{HoldingPb}) = (;symbol = "", quantity = zero(Float32), security_type = SecurityTypePb.EQUITY)
PB.field_numbers(::Type{HoldingPb}) = (;symbol = 1, quantity = 2, security_type = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:HoldingPb}, _endpos::Int=0, _group::Bool=false)
    symbol = ""
    quantity = zero(Float32)
    security_type = SecurityTypePb.EQUITY
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            symbol = PB.decode(d, String)
        elseif field_number == 2
            quantity = PB.decode(d, Float32)
        elseif field_number == 3
            security_type = PB.decode(d, SecurityTypePb.T)
        else
            Base.skip(d, wire_type)
        end
    end
    return HoldingPb(symbol, quantity, security_type)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::HoldingPb)
    initpos = position(e.io)
    !isempty(x.symbol) && PB.encode(e, 1, x.symbol)
    x.quantity !== zero(Float32) && PB.encode(e, 2, x.quantity)
    x.security_type != SecurityTypePb.EQUITY && PB.encode(e, 3, x.security_type)
    return position(e.io) - initpos
end
function PB._encoded_size(x::HoldingPb)
    encoded_size = 0
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 1))
    x.quantity !== zero(Float32) && (encoded_size += PB._encoded_size(x.quantity, 2))
    x.security_type != SecurityTypePb.EQUITY && (encoded_size += PB._encoded_size(x.security_type, 3))
    return encoded_size
end

struct TradePb
    ts::String
    symbol::String
    security_type::SecurityTypePb.T
    price::Float32
    price_underlying::Float32
end
PB.default_values(::Type{TradePb}) = (;ts = "", symbol = "", security_type = SecurityTypePb.EQUITY, price = zero(Float32), price_underlying = zero(Float32))
PB.field_numbers(::Type{TradePb}) = (;ts = 1, symbol = 2, security_type = 3, price = 4, price_underlying = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TradePb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    symbol = ""
    security_type = SecurityTypePb.EQUITY
    price = zero(Float32)
    price_underlying = zero(Float32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            symbol = PB.decode(d, String)
        elseif field_number == 3
            security_type = PB.decode(d, SecurityTypePb.T)
        elseif field_number == 4
            price = PB.decode(d, Float32)
        elseif field_number == 5
            price_underlying = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return TradePb(ts, symbol, security_type, price, price_underlying)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TradePb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.symbol) && PB.encode(e, 2, x.symbol)
    x.security_type != SecurityTypePb.EQUITY && PB.encode(e, 3, x.security_type)
    x.price !== zero(Float32) && PB.encode(e, 4, x.price)
    x.price_underlying !== zero(Float32) && PB.encode(e, 5, x.price_underlying)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TradePb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 2))
    x.security_type != SecurityTypePb.EQUITY && (encoded_size += PB._encoded_size(x.security_type, 3))
    x.price !== zero(Float32) && (encoded_size += PB._encoded_size(x.price, 4))
    x.price_underlying !== zero(Float32) && (encoded_size += PB._encoded_size(x.price_underlying, 5))
    return encoded_size
end

struct QuotePb
    ts::String
    symbol::String
    security_type::SecurityTypePb.T
    bid::Float32
    ask::Float32
    price_underlying::Float32
end
PB.default_values(::Type{QuotePb}) = (;ts = "", symbol = "", security_type = SecurityTypePb.EQUITY, bid = zero(Float32), ask = zero(Float32), price_underlying = zero(Float32))
PB.field_numbers(::Type{QuotePb}) = (;ts = 1, symbol = 2, security_type = 3, bid = 4, ask = 5, price_underlying = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:QuotePb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    symbol = ""
    security_type = SecurityTypePb.EQUITY
    bid = zero(Float32)
    ask = zero(Float32)
    price_underlying = zero(Float32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            symbol = PB.decode(d, String)
        elseif field_number == 3
            security_type = PB.decode(d, SecurityTypePb.T)
        elseif field_number == 4
            bid = PB.decode(d, Float32)
        elseif field_number == 5
            ask = PB.decode(d, Float32)
        elseif field_number == 6
            price_underlying = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return QuotePb(ts, symbol, security_type, bid, ask, price_underlying)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::QuotePb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.symbol) && PB.encode(e, 2, x.symbol)
    x.security_type != SecurityTypePb.EQUITY && PB.encode(e, 3, x.security_type)
    x.bid !== zero(Float32) && PB.encode(e, 4, x.bid)
    x.ask !== zero(Float32) && PB.encode(e, 5, x.ask)
    x.price_underlying !== zero(Float32) && PB.encode(e, 6, x.price_underlying)
    return position(e.io) - initpos
end
function PB._encoded_size(x::QuotePb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 2))
    x.security_type != SecurityTypePb.EQUITY && (encoded_size += PB._encoded_size(x.security_type, 3))
    x.bid !== zero(Float32) && (encoded_size += PB._encoded_size(x.bid, 4))
    x.ask !== zero(Float32) && (encoded_size += PB._encoded_size(x.ask, 5))
    x.price_underlying !== zero(Float32) && (encoded_size += PB._encoded_size(x.price_underlying, 6))
    return encoded_size
end

struct MarketDataSnapByUnderlyingPb
    ts::String
    underlying::String
    underlying_price::Float32
    option_quotes::Dict{String,OptionQuotePb}
end
PB.default_values(::Type{MarketDataSnapByUnderlyingPb}) = (;ts = "", underlying = "", underlying_price = zero(Float32), option_quotes = Dict{String,OptionQuotePb}())
PB.field_numbers(::Type{MarketDataSnapByUnderlyingPb}) = (;ts = 1, underlying = 2, underlying_price = 3, option_quotes = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MarketDataSnapByUnderlyingPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    underlying_price = zero(Float32)
    option_quotes = Dict{String,OptionQuotePb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            underlying_price = PB.decode(d, Float32)
        elseif field_number == 4
            PB.decode!(d, option_quotes)
        else
            Base.skip(d, wire_type)
        end
    end
    return MarketDataSnapByUnderlyingPb(ts, underlying, underlying_price, option_quotes)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MarketDataSnapByUnderlyingPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    x.underlying_price !== zero(Float32) && PB.encode(e, 3, x.underlying_price)
    !isempty(x.option_quotes) && PB.encode(e, 4, x.option_quotes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MarketDataSnapByUnderlyingPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    x.underlying_price !== zero(Float32) && (encoded_size += PB._encoded_size(x.underlying_price, 3))
    !isempty(x.option_quotes) && (encoded_size += PB._encoded_size(x.option_quotes, 4))
    return encoded_size
end

struct TradesPb
    symbol::String
    security_type::SecurityTypePb.T
    trades::Vector{TradePb}
end
PB.default_values(::Type{TradesPb}) = (;symbol = "", security_type = SecurityTypePb.EQUITY, trades = Vector{TradePb}())
PB.field_numbers(::Type{TradesPb}) = (;symbol = 1, security_type = 2, trades = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TradesPb}, _endpos::Int=0, _group::Bool=false)
    symbol = ""
    security_type = SecurityTypePb.EQUITY
    trades = PB.BufferedVector{TradePb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            symbol = PB.decode(d, String)
        elseif field_number == 2
            security_type = PB.decode(d, SecurityTypePb.T)
        elseif field_number == 3
            PB.decode!(d, trades)
        else
            Base.skip(d, wire_type)
        end
    end
    return TradesPb(symbol, security_type, trades[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TradesPb)
    initpos = position(e.io)
    !isempty(x.symbol) && PB.encode(e, 1, x.symbol)
    x.security_type != SecurityTypePb.EQUITY && PB.encode(e, 2, x.security_type)
    !isempty(x.trades) && PB.encode(e, 3, x.trades)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TradesPb)
    encoded_size = 0
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 1))
    x.security_type != SecurityTypePb.EQUITY && (encoded_size += PB._encoded_size(x.security_type, 2))
    !isempty(x.trades) && (encoded_size += PB._encoded_size(x.trades, 3))
    return encoded_size
end

struct QuotesPb
    symbol::String
    security_type::SecurityTypePb.T
    quotes::Vector{QuotePb}
end
PB.default_values(::Type{QuotesPb}) = (;symbol = "", security_type = SecurityTypePb.EQUITY, quotes = Vector{QuotePb}())
PB.field_numbers(::Type{QuotesPb}) = (;symbol = 1, security_type = 2, quotes = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:QuotesPb}, _endpos::Int=0, _group::Bool=false)
    symbol = ""
    security_type = SecurityTypePb.EQUITY
    quotes = PB.BufferedVector{QuotePb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            symbol = PB.decode(d, String)
        elseif field_number == 2
            security_type = PB.decode(d, SecurityTypePb.T)
        elseif field_number == 3
            PB.decode!(d, quotes)
        else
            Base.skip(d, wire_type)
        end
    end
    return QuotesPb(symbol, security_type, quotes[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::QuotesPb)
    initpos = position(e.io)
    !isempty(x.symbol) && PB.encode(e, 1, x.symbol)
    x.security_type != SecurityTypePb.EQUITY && PB.encode(e, 2, x.security_type)
    !isempty(x.quotes) && PB.encode(e, 3, x.quotes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::QuotesPb)
    encoded_size = 0
    !isempty(x.symbol) && (encoded_size += PB._encoded_size(x.symbol, 1))
    x.security_type != SecurityTypePb.EQUITY && (encoded_size += PB._encoded_size(x.security_type, 2))
    !isempty(x.quotes) && (encoded_size += PB._encoded_size(x.quotes, 3))
    return encoded_size
end

struct MarketDataHistoryPb
    ts::String
    ts_start::String
    ts_end::String
    underlying::String
    quotes::Dict{String,QuotesPb}
    trades::Dict{String,TradesPb}
end
PB.default_values(::Type{MarketDataHistoryPb}) = (;ts = "", ts_start = "", ts_end = "", underlying = "", quotes = Dict{String,QuotesPb}(), trades = Dict{String,TradesPb}())
PB.field_numbers(::Type{MarketDataHistoryPb}) = (;ts = 1, ts_start = 2, ts_end = 3, underlying = 4, quotes = 5, trades = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MarketDataHistoryPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    ts_start = ""
    ts_end = ""
    underlying = ""
    quotes = Dict{String,QuotesPb}()
    trades = Dict{String,TradesPb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            ts_start = PB.decode(d, String)
        elseif field_number == 3
            ts_end = PB.decode(d, String)
        elseif field_number == 4
            underlying = PB.decode(d, String)
        elseif field_number == 5
            PB.decode!(d, quotes)
        elseif field_number == 6
            PB.decode!(d, trades)
        else
            Base.skip(d, wire_type)
        end
    end
    return MarketDataHistoryPb(ts, ts_start, ts_end, underlying, quotes, trades)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MarketDataHistoryPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.ts_start) && PB.encode(e, 2, x.ts_start)
    !isempty(x.ts_end) && PB.encode(e, 3, x.ts_end)
    !isempty(x.underlying) && PB.encode(e, 4, x.underlying)
    !isempty(x.quotes) && PB.encode(e, 5, x.quotes)
    !isempty(x.trades) && PB.encode(e, 6, x.trades)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MarketDataHistoryPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.ts_start) && (encoded_size += PB._encoded_size(x.ts_start, 2))
    !isempty(x.ts_end) && (encoded_size += PB._encoded_size(x.ts_end, 3))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 4))
    !isempty(x.quotes) && (encoded_size += PB._encoded_size(x.quotes, 5))
    !isempty(x.trades) && (encoded_size += PB._encoded_size(x.trades, 6))
    return encoded_size
end
end # module
