# Autogenerated using ProtoBuf.jl v1.3.0
# original file: PfRiskScenarios.proto (proto3 syntax)

module PfRiskScenarios_pb

import ..Common_pb
import ..RequestSSVICalibration_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export RequestPfRiskScenariosPb, PfRiskScenarioPb, ResponsePfRiskScenariosPb


struct RequestPfRiskScenariosPb
    ts::String
    underlying::String
    holdings::Dict{String,Common_pb.HoldingPb}
    market_data_snaps::Vector{Common_pb.MarketDataSnapByUnderlyingPb}
    params::Vector{RequestSSVICalibration_pb.SSVIParamsPb}
    scoped_symbols::Vector{String}
end
PB.default_values(::Type{RequestPfRiskScenariosPb}) = (;ts = "", underlying = "", holdings = Dict{String,Common_pb.HoldingPb}(), market_data_snaps = Vector{Common_pb.MarketDataSnapByUnderlyingPb}(), params = Vector{RequestSSVICalibration_pb.SSVIParamsPb}(), scoped_symbols = Vector{String}())
PB.field_numbers(::Type{RequestPfRiskScenariosPb}) = (;ts = 1, underlying = 2, holdings = 3, market_data_snaps = 4, params = 5, scoped_symbols = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RequestPfRiskScenariosPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    holdings = Dict{String,Common_pb.HoldingPb}()
    market_data_snaps = PB.BufferedVector{Common_pb.MarketDataSnapByUnderlyingPb}()
    params = PB.BufferedVector{RequestSSVICalibration_pb.SSVIParamsPb}()
    scoped_symbols = PB.BufferedVector{String}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, holdings)
        elseif field_number == 4
            PB.decode!(d, market_data_snaps)
        elseif field_number == 5
            PB.decode!(d, params)
        elseif field_number == 6
            PB.decode!(d, scoped_symbols)
        else
            Base.skip(d, wire_type)
        end
    end
    return RequestPfRiskScenariosPb(ts, underlying, holdings, market_data_snaps[], params[], scoped_symbols[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RequestPfRiskScenariosPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.holdings) && PB.encode(e, 3, x.holdings)
    !isempty(x.market_data_snaps) && PB.encode(e, 4, x.market_data_snaps)
    !isempty(x.params) && PB.encode(e, 5, x.params)
    !isempty(x.scoped_symbols) && PB.encode(e, 6, x.scoped_symbols)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RequestPfRiskScenariosPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.holdings) && (encoded_size += PB._encoded_size(x.holdings, 3))
    !isempty(x.market_data_snaps) && (encoded_size += PB._encoded_size(x.market_data_snaps, 4))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 5))
    !isempty(x.scoped_symbols) && (encoded_size += PB._encoded_size(x.scoped_symbols, 6))
    return encoded_size
end

struct PfRiskScenarioPb
    underlying::String
    holdings_hedge::Dict{String,Common_pb.HoldingPb}
    dPL::Float64
    score::Float64
    dPLEqHedged::Float64
    iv_enter::Dict{String,Float64}
    holdings_current::Dict{String,Common_pb.HoldingPb}
end
PB.default_values(::Type{PfRiskScenarioPb}) = (;underlying = "", holdings_hedge = Dict{String,Common_pb.HoldingPb}(), dPL = zero(Float64), score = zero(Float64), dPLEqHedged = zero(Float64), iv_enter = Dict{String,Float64}(), holdings_current = Dict{String,Common_pb.HoldingPb}())
PB.field_numbers(::Type{PfRiskScenarioPb}) = (;underlying = 1, holdings_hedge = 2, dPL = 3, score = 4, dPLEqHedged = 5, iv_enter = 6, holdings_current = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:PfRiskScenarioPb}, _endpos::Int=0, _group::Bool=false)
    underlying = ""
    holdings_hedge = Dict{String,Common_pb.HoldingPb}()
    dPL = zero(Float64)
    score = zero(Float64)
    dPLEqHedged = zero(Float64)
    iv_enter = Dict{String,Float64}()
    holdings_current = Dict{String,Common_pb.HoldingPb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            underlying = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, holdings_hedge)
        elseif field_number == 3
            dPL = PB.decode(d, Float64)
        elseif field_number == 4
            score = PB.decode(d, Float64)
        elseif field_number == 5
            dPLEqHedged = PB.decode(d, Float64)
        elseif field_number == 6
            PB.decode!(d, iv_enter)
        elseif field_number == 7
            PB.decode!(d, holdings_current)
        else
            Base.skip(d, wire_type)
        end
    end
    return PfRiskScenarioPb(underlying, holdings_hedge, dPL, score, dPLEqHedged, iv_enter, holdings_current)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::PfRiskScenarioPb)
    initpos = position(e.io)
    !isempty(x.underlying) && PB.encode(e, 1, x.underlying)
    !isempty(x.holdings_hedge) && PB.encode(e, 2, x.holdings_hedge)
    x.dPL !== zero(Float64) && PB.encode(e, 3, x.dPL)
    x.score !== zero(Float64) && PB.encode(e, 4, x.score)
    x.dPLEqHedged !== zero(Float64) && PB.encode(e, 5, x.dPLEqHedged)
    !isempty(x.iv_enter) && PB.encode(e, 6, x.iv_enter)
    !isempty(x.holdings_current) && PB.encode(e, 7, x.holdings_current)
    return position(e.io) - initpos
end
function PB._encoded_size(x::PfRiskScenarioPb)
    encoded_size = 0
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 1))
    !isempty(x.holdings_hedge) && (encoded_size += PB._encoded_size(x.holdings_hedge, 2))
    x.dPL !== zero(Float64) && (encoded_size += PB._encoded_size(x.dPL, 3))
    x.score !== zero(Float64) && (encoded_size += PB._encoded_size(x.score, 4))
    x.dPLEqHedged !== zero(Float64) && (encoded_size += PB._encoded_size(x.dPLEqHedged, 5))
    !isempty(x.iv_enter) && (encoded_size += PB._encoded_size(x.iv_enter, 6))
    !isempty(x.holdings_current) && (encoded_size += PB._encoded_size(x.holdings_current, 7))
    return encoded_size
end

struct ResponsePfRiskScenariosPb
    ts::String
    underlying::String
    pf_risk_scenarios::Vector{PfRiskScenarioPb}
end
PB.default_values(::Type{ResponsePfRiskScenariosPb}) = (;ts = "", underlying = "", pf_risk_scenarios = Vector{PfRiskScenarioPb}())
PB.field_numbers(::Type{ResponsePfRiskScenariosPb}) = (;ts = 1, underlying = 2, pf_risk_scenarios = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResponsePfRiskScenariosPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    pf_risk_scenarios = PB.BufferedVector{PfRiskScenarioPb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, pf_risk_scenarios)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResponsePfRiskScenariosPb(ts, underlying, pf_risk_scenarios[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResponsePfRiskScenariosPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.pf_risk_scenarios) && PB.encode(e, 3, x.pf_risk_scenarios)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResponsePfRiskScenariosPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.pf_risk_scenarios) && (encoded_size += PB._encoded_size(x.pf_risk_scenarios, 3))
    return encoded_size
end
end # module
