# Autogenerated using ProtoBuf.jl v1.3.0
# original file: RequestTargetPortfolios.proto (proto3 syntax)

module RequestTargetPortfolios_pb

import ..Common_pb
import ..StressTestDs_pb
import ..RequestSSVICalibration_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export RequestTargetPortfoliosPb, TargetPortfolioPb, ResponseTargetPortfoliosPb


struct RequestTargetPortfoliosPb
    ts::String
    underlying::String
    holdings::Dict{String,Common_pb.HoldingPb}
    market_data_snaps::Vector{Common_pb.MarketDataSnapByUnderlyingPb}
    n_contracts::Int32
    params::Vector{RequestSSVICalibration_pb.SSVIParamsPb}
    scoped_symbols::Vector{String}
end
PB.default_values(::Type{RequestTargetPortfoliosPb}) = (;ts = "", underlying = "", holdings = Dict{String,Common_pb.HoldingPb}(), market_data_snaps = Vector{Common_pb.MarketDataSnapByUnderlyingPb}(), n_contracts = zero(Int32), params = Vector{RequestSSVICalibration_pb.SSVIParamsPb}(), scoped_symbols = Vector{String}())
PB.field_numbers(::Type{RequestTargetPortfoliosPb}) = (;ts = 1, underlying = 2, holdings = 3, market_data_snaps = 4, n_contracts = 5, params = 6, scoped_symbols = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RequestTargetPortfoliosPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    holdings = Dict{String,Common_pb.HoldingPb}()
    market_data_snaps = PB.BufferedVector{Common_pb.MarketDataSnapByUnderlyingPb}()
    n_contracts = zero(Int32)
    params = PB.BufferedVector{RequestSSVICalibration_pb.SSVIParamsPb}()
    scoped_symbols = PB.BufferedVector{String}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, holdings)
        elseif field_number == 4
            PB.decode!(d, market_data_snaps)
        elseif field_number == 5
            n_contracts = PB.decode(d, Int32)
        elseif field_number == 6
            PB.decode!(d, params)
        elseif field_number == 7
            PB.decode!(d, scoped_symbols)
        else
            Base.skip(d, wire_type)
        end
    end
    return RequestTargetPortfoliosPb(ts, underlying, holdings, market_data_snaps[], n_contracts, params[], scoped_symbols[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RequestTargetPortfoliosPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.holdings) && PB.encode(e, 3, x.holdings)
    !isempty(x.market_data_snaps) && PB.encode(e, 4, x.market_data_snaps)
    x.n_contracts != zero(Int32) && PB.encode(e, 5, x.n_contracts)
    !isempty(x.params) && PB.encode(e, 6, x.params)
    !isempty(x.scoped_symbols) && PB.encode(e, 7, x.scoped_symbols)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RequestTargetPortfoliosPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.holdings) && (encoded_size += PB._encoded_size(x.holdings, 3))
    !isempty(x.market_data_snaps) && (encoded_size += PB._encoded_size(x.market_data_snaps, 4))
    x.n_contracts != zero(Int32) && (encoded_size += PB._encoded_size(x.n_contracts, 5))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 6))
    !isempty(x.scoped_symbols) && (encoded_size += PB._encoded_size(x.scoped_symbols, 7))
    return encoded_size
end

struct TargetPortfolioPb
    underlying::String
    holdings::Dict{String,Common_pb.HoldingPb}
    objective::Float64
    ivs::Dict{String,Float64}
    result_stress_test_ds::Union{Nothing,StressTestDs_pb.ResultStressTestDsPb}
end
PB.default_values(::Type{TargetPortfolioPb}) = (;underlying = "", holdings = Dict{String,Common_pb.HoldingPb}(), objective = zero(Float64), ivs = Dict{String,Float64}(), result_stress_test_ds = nothing)
PB.field_numbers(::Type{TargetPortfolioPb}) = (;underlying = 1, holdings = 2, objective = 3, ivs = 4, result_stress_test_ds = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TargetPortfolioPb}, _endpos::Int=0, _group::Bool=false)
    underlying = ""
    holdings = Dict{String,Common_pb.HoldingPb}()
    objective = zero(Float64)
    ivs = Dict{String,Float64}()
    result_stress_test_ds = Ref{Union{Nothing,StressTestDs_pb.ResultStressTestDsPb}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            underlying = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, holdings)
        elseif field_number == 3
            objective = PB.decode(d, Float64)
        elseif field_number == 4
            PB.decode!(d, ivs)
        elseif field_number == 5
            PB.decode!(d, result_stress_test_ds)
        else
            Base.skip(d, wire_type)
        end
    end
    return TargetPortfolioPb(underlying, holdings, objective, ivs, result_stress_test_ds[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TargetPortfolioPb)
    initpos = position(e.io)
    !isempty(x.underlying) && PB.encode(e, 1, x.underlying)
    !isempty(x.holdings) && PB.encode(e, 2, x.holdings)
    x.objective !== zero(Float64) && PB.encode(e, 3, x.objective)
    !isempty(x.ivs) && PB.encode(e, 4, x.ivs)
    !isnothing(x.result_stress_test_ds) && PB.encode(e, 5, x.result_stress_test_ds)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TargetPortfolioPb)
    encoded_size = 0
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 1))
    !isempty(x.holdings) && (encoded_size += PB._encoded_size(x.holdings, 2))
    x.objective !== zero(Float64) && (encoded_size += PB._encoded_size(x.objective, 3))
    !isempty(x.ivs) && (encoded_size += PB._encoded_size(x.ivs, 4))
    !isnothing(x.result_stress_test_ds) && (encoded_size += PB._encoded_size(x.result_stress_test_ds, 5))
    return encoded_size
end

struct ResponseTargetPortfoliosPb
    ts::String
    underlying::String
    target_portfolios::Vector{TargetPortfolioPb}
    is_last_transmission::Bool
end
PB.default_values(::Type{ResponseTargetPortfoliosPb}) = (;ts = "", underlying = "", target_portfolios = Vector{TargetPortfolioPb}(), is_last_transmission = false)
PB.field_numbers(::Type{ResponseTargetPortfoliosPb}) = (;ts = 1, underlying = 2, target_portfolios = 3, is_last_transmission = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResponseTargetPortfoliosPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    target_portfolios = PB.BufferedVector{TargetPortfolioPb}()
    is_last_transmission = false
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, target_portfolios)
        elseif field_number == 4
            is_last_transmission = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResponseTargetPortfoliosPb(ts, underlying, target_portfolios[], is_last_transmission)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResponseTargetPortfoliosPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.target_portfolios) && PB.encode(e, 3, x.target_portfolios)
    x.is_last_transmission != false && PB.encode(e, 4, x.is_last_transmission)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResponseTargetPortfoliosPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.target_portfolios) && (encoded_size += PB._encoded_size(x.target_portfolios, 3))
    x.is_last_transmission != false && (encoded_size += PB._encoded_size(x.is_last_transmission, 4))
    return encoded_size
end
end # module
