# Autogenerated using ProtoBuf.jl v1.3.0
# original file: RequestKalmanInit.proto (proto3 syntax)

module RequestKalmanInit_pb

import ..Common_pb
import ..RequestSSVICalibration_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export RequestKalmanInitPb, ResponseKalmanInitPb


struct RequestKalmanInitPb
    underlying::String
    date_fit_start::String
    date_fit_end::String
    ts::String
end
PB.default_values(::Type{RequestKalmanInitPb}) = (;underlying = "", date_fit_start = "", date_fit_end = "", ts = "")
PB.field_numbers(::Type{RequestKalmanInitPb}) = (;underlying = 1, date_fit_start = 2, date_fit_end = 3, ts = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RequestKalmanInitPb}, _endpos::Int=0, _group::Bool=false)
    underlying = ""
    date_fit_start = ""
    date_fit_end = ""
    ts = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            underlying = PB.decode(d, String)
        elseif field_number == 2
            date_fit_start = PB.decode(d, String)
        elseif field_number == 3
            date_fit_end = PB.decode(d, String)
        elseif field_number == 4
            ts = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return RequestKalmanInitPb(underlying, date_fit_start, date_fit_end, ts)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RequestKalmanInitPb)
    initpos = position(e.io)
    !isempty(x.underlying) && PB.encode(e, 1, x.underlying)
    !isempty(x.date_fit_start) && PB.encode(e, 2, x.date_fit_start)
    !isempty(x.date_fit_end) && PB.encode(e, 3, x.date_fit_end)
    !isempty(x.ts) && PB.encode(e, 4, x.ts)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RequestKalmanInitPb)
    encoded_size = 0
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 1))
    !isempty(x.date_fit_start) && (encoded_size += PB._encoded_size(x.date_fit_start, 2))
    !isempty(x.date_fit_end) && (encoded_size += PB._encoded_size(x.date_fit_end, 3))
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 4))
    return encoded_size
end

struct ResponseKalmanInitPb
    request::Union{Nothing,RequestKalmanInitPb}
    init_state::Vector{RequestSSVICalibration_pb.SSVIParamsPb}
    init_covariance::Vector{Common_pb.VectorDoublePb}
end
PB.default_values(::Type{ResponseKalmanInitPb}) = (;request = nothing, init_state = Vector{RequestSSVICalibration_pb.SSVIParamsPb}(), init_covariance = Vector{Common_pb.VectorDoublePb}())
PB.field_numbers(::Type{ResponseKalmanInitPb}) = (;request = 1, init_state = 2, init_covariance = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResponseKalmanInitPb}, _endpos::Int=0, _group::Bool=false)
    request = Ref{Union{Nothing,RequestKalmanInitPb}}(nothing)
    init_state = PB.BufferedVector{RequestSSVICalibration_pb.SSVIParamsPb}()
    init_covariance = PB.BufferedVector{Common_pb.VectorDoublePb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, request)
        elseif field_number == 2
            PB.decode!(d, init_state)
        elseif field_number == 3
            PB.decode!(d, init_covariance)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResponseKalmanInitPb(request[], init_state[], init_covariance[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResponseKalmanInitPb)
    initpos = position(e.io)
    !isnothing(x.request) && PB.encode(e, 1, x.request)
    !isempty(x.init_state) && PB.encode(e, 2, x.init_state)
    !isempty(x.init_covariance) && PB.encode(e, 3, x.init_covariance)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResponseKalmanInitPb)
    encoded_size = 0
    !isnothing(x.request) && (encoded_size += PB._encoded_size(x.request, 1))
    !isempty(x.init_state) && (encoded_size += PB._encoded_size(x.init_state, 2))
    !isempty(x.init_covariance) && (encoded_size += PB._encoded_size(x.init_covariance, 3))
    return encoded_size
end
end # module
