# Autogenerated using ProtoBuf.jl v1.3.0
# original file: RequestSSVICalibration.proto (proto3 syntax)

module RequestSSVICalibration_pb

import ..Common_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export SSVIModelParamsPb, RequestSSVICalibrationPb, SSVIParamsPb, SSVIParamsByRightPb
export ResponseSSVICalibrationPb


struct SSVIModelParamsPb
    theta::Float64
    rho::Float64
    psi::Float64
end
PB.default_values(::Type{SSVIModelParamsPb}) = (;theta = zero(Float64), rho = zero(Float64), psi = zero(Float64))
PB.field_numbers(::Type{SSVIModelParamsPb}) = (;theta = 1, rho = 2, psi = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SSVIModelParamsPb}, _endpos::Int=0, _group::Bool=false)
    theta = zero(Float64)
    rho = zero(Float64)
    psi = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            theta = PB.decode(d, Float64)
        elseif field_number == 2
            rho = PB.decode(d, Float64)
        elseif field_number == 3
            psi = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return SSVIModelParamsPb(theta, rho, psi)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SSVIModelParamsPb)
    initpos = position(e.io)
    x.theta !== zero(Float64) && PB.encode(e, 1, x.theta)
    x.rho !== zero(Float64) && PB.encode(e, 2, x.rho)
    x.psi !== zero(Float64) && PB.encode(e, 3, x.psi)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SSVIModelParamsPb)
    encoded_size = 0
    x.theta !== zero(Float64) && (encoded_size += PB._encoded_size(x.theta, 1))
    x.rho !== zero(Float64) && (encoded_size += PB._encoded_size(x.rho, 2))
    x.psi !== zero(Float64) && (encoded_size += PB._encoded_size(x.psi, 3))
    return encoded_size
end

struct RequestSSVICalibrationPb
    ts::String
    underlying::String
    market_data_history::Union{Nothing,Common_pb.MarketDataHistoryPb}
end
PB.default_values(::Type{RequestSSVICalibrationPb}) = (;ts = "", underlying = "", market_data_history = nothing)
PB.field_numbers(::Type{RequestSSVICalibrationPb}) = (;ts = 1, underlying = 2, market_data_history = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RequestSSVICalibrationPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    market_data_history = Ref{Union{Nothing,Common_pb.MarketDataHistoryPb}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, market_data_history)
        else
            Base.skip(d, wire_type)
        end
    end
    return RequestSSVICalibrationPb(ts, underlying, market_data_history[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RequestSSVICalibrationPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isnothing(x.market_data_history) && PB.encode(e, 3, x.market_data_history)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RequestSSVICalibrationPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isnothing(x.market_data_history) && (encoded_size += PB._encoded_size(x.market_data_history, 3))
    return encoded_size
end

struct SSVIParamsPb
    underlying::String
    tenor_dt::String
    model_params::Union{Nothing,SSVIModelParamsPb}
end
PB.default_values(::Type{SSVIParamsPb}) = (;underlying = "", tenor_dt = "", model_params = nothing)
PB.field_numbers(::Type{SSVIParamsPb}) = (;underlying = 1, tenor_dt = 2, model_params = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SSVIParamsPb}, _endpos::Int=0, _group::Bool=false)
    underlying = ""
    tenor_dt = ""
    model_params = Ref{Union{Nothing,SSVIModelParamsPb}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            underlying = PB.decode(d, String)
        elseif field_number == 2
            tenor_dt = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, model_params)
        else
            Base.skip(d, wire_type)
        end
    end
    return SSVIParamsPb(underlying, tenor_dt, model_params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SSVIParamsPb)
    initpos = position(e.io)
    !isempty(x.underlying) && PB.encode(e, 1, x.underlying)
    !isempty(x.tenor_dt) && PB.encode(e, 2, x.tenor_dt)
    !isnothing(x.model_params) && PB.encode(e, 3, x.model_params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SSVIParamsPb)
    encoded_size = 0
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 1))
    !isempty(x.tenor_dt) && (encoded_size += PB._encoded_size(x.tenor_dt, 2))
    !isnothing(x.model_params) && (encoded_size += PB._encoded_size(x.model_params, 3))
    return encoded_size
end

struct SSVIParamsByRightPb
    underlying::String
    right::Common_pb.OptionRightPb.T
    tenor_dt::String
    model_params::Union{Nothing,SSVIModelParamsPb}
end
PB.default_values(::Type{SSVIParamsByRightPb}) = (;underlying = "", right = Common_pb.OptionRightPb.CALL, tenor_dt = "", model_params = nothing)
PB.field_numbers(::Type{SSVIParamsByRightPb}) = (;underlying = 1, right = 2, tenor_dt = 3, model_params = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SSVIParamsByRightPb}, _endpos::Int=0, _group::Bool=false)
    underlying = ""
    right = Common_pb.OptionRightPb.CALL
    tenor_dt = ""
    model_params = Ref{Union{Nothing,SSVIModelParamsPb}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            underlying = PB.decode(d, String)
        elseif field_number == 2
            right = PB.decode(d, Common_pb.OptionRightPb.T)
        elseif field_number == 3
            tenor_dt = PB.decode(d, String)
        elseif field_number == 4
            PB.decode!(d, model_params)
        else
            Base.skip(d, wire_type)
        end
    end
    return SSVIParamsByRightPb(underlying, right, tenor_dt, model_params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SSVIParamsByRightPb)
    initpos = position(e.io)
    !isempty(x.underlying) && PB.encode(e, 1, x.underlying)
    x.right != Common_pb.OptionRightPb.CALL && PB.encode(e, 2, x.right)
    !isempty(x.tenor_dt) && PB.encode(e, 3, x.tenor_dt)
    !isnothing(x.model_params) && PB.encode(e, 4, x.model_params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SSVIParamsByRightPb)
    encoded_size = 0
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 1))
    x.right != Common_pb.OptionRightPb.CALL && (encoded_size += PB._encoded_size(x.right, 2))
    !isempty(x.tenor_dt) && (encoded_size += PB._encoded_size(x.tenor_dt, 3))
    !isnothing(x.model_params) && (encoded_size += PB._encoded_size(x.model_params, 4))
    return encoded_size
end

struct ResponseSSVICalibrationPb
    ts::String
    request::Union{Nothing,RequestSSVICalibrationPb}
    params::Vector{SSVIParamsPb}
end
PB.default_values(::Type{ResponseSSVICalibrationPb}) = (;ts = "", request = nothing, params = Vector{SSVIParamsPb}())
PB.field_numbers(::Type{ResponseSSVICalibrationPb}) = (;ts = 1, request = 2, params = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResponseSSVICalibrationPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    request = Ref{Union{Nothing,RequestSSVICalibrationPb}}(nothing)
    params = PB.BufferedVector{SSVIParamsPb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, request)
        elseif field_number == 3
            PB.decode!(d, params)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResponseSSVICalibrationPb(ts, request[], params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResponseSSVICalibrationPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isnothing(x.request) && PB.encode(e, 2, x.request)
    !isempty(x.params) && PB.encode(e, 3, x.params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResponseSSVICalibrationPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isnothing(x.request) && (encoded_size += PB._encoded_size(x.request, 2))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 3))
    return encoded_size
end
end # module
