# Autogenerated using ProtoBuf.jl v1.3.0
# original file: StressTestDs.proto (proto3 syntax)

module StressTestDs_pb

import ..Common_pb
import ..RequestSSVICalibration_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ResultStressTestDsPb, RequestStressTestDsPb


struct ResultStressTestDsPb
    ts::String
    underlying::String
    holdings::Dict{String,Common_pb.HoldingPb}
    ds_dnlv::Dict{String,Float64}
    delta_total::Float64
    delta_total_across_ds::Float64
    weighted_dnlv::Float64
    marginal_utility_by_holding::Dict{String,Float64}
    total_objective::Float64
    marginal_scaled_objective_by_holding::Dict{String,Float64}
end
PB.default_values(::Type{ResultStressTestDsPb}) = (;ts = "", underlying = "", holdings = Dict{String,Common_pb.HoldingPb}(), ds_dnlv = Dict{String,Float64}(), delta_total = zero(Float64), delta_total_across_ds = zero(Float64), weighted_dnlv = zero(Float64), marginal_utility_by_holding = Dict{String,Float64}(), total_objective = zero(Float64), marginal_scaled_objective_by_holding = Dict{String,Float64}())
PB.field_numbers(::Type{ResultStressTestDsPb}) = (;ts = 1, underlying = 2, holdings = 3, ds_dnlv = 4, delta_total = 5, delta_total_across_ds = 6, weighted_dnlv = 7, marginal_utility_by_holding = 8, total_objective = 9, marginal_scaled_objective_by_holding = 10)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResultStressTestDsPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    holdings = Dict{String,Common_pb.HoldingPb}()
    ds_dnlv = Dict{String,Float64}()
    delta_total = zero(Float64)
    delta_total_across_ds = zero(Float64)
    weighted_dnlv = zero(Float64)
    marginal_utility_by_holding = Dict{String,Float64}()
    total_objective = zero(Float64)
    marginal_scaled_objective_by_holding = Dict{String,Float64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, holdings)
        elseif field_number == 4
            PB.decode!(d, ds_dnlv)
        elseif field_number == 5
            delta_total = PB.decode(d, Float64)
        elseif field_number == 6
            delta_total_across_ds = PB.decode(d, Float64)
        elseif field_number == 7
            weighted_dnlv = PB.decode(d, Float64)
        elseif field_number == 8
            PB.decode!(d, marginal_utility_by_holding)
        elseif field_number == 9
            total_objective = PB.decode(d, Float64)
        elseif field_number == 10
            PB.decode!(d, marginal_scaled_objective_by_holding)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResultStressTestDsPb(ts, underlying, holdings, ds_dnlv, delta_total, delta_total_across_ds, weighted_dnlv, marginal_utility_by_holding, total_objective, marginal_scaled_objective_by_holding)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResultStressTestDsPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.holdings) && PB.encode(e, 3, x.holdings)
    !isempty(x.ds_dnlv) && PB.encode(e, 4, x.ds_dnlv)
    x.delta_total !== zero(Float64) && PB.encode(e, 5, x.delta_total)
    x.delta_total_across_ds !== zero(Float64) && PB.encode(e, 6, x.delta_total_across_ds)
    x.weighted_dnlv !== zero(Float64) && PB.encode(e, 7, x.weighted_dnlv)
    !isempty(x.marginal_utility_by_holding) && PB.encode(e, 8, x.marginal_utility_by_holding)
    x.total_objective !== zero(Float64) && PB.encode(e, 9, x.total_objective)
    !isempty(x.marginal_scaled_objective_by_holding) && PB.encode(e, 10, x.marginal_scaled_objective_by_holding)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResultStressTestDsPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.holdings) && (encoded_size += PB._encoded_size(x.holdings, 3))
    !isempty(x.ds_dnlv) && (encoded_size += PB._encoded_size(x.ds_dnlv, 4))
    x.delta_total !== zero(Float64) && (encoded_size += PB._encoded_size(x.delta_total, 5))
    x.delta_total_across_ds !== zero(Float64) && (encoded_size += PB._encoded_size(x.delta_total_across_ds, 6))
    x.weighted_dnlv !== zero(Float64) && (encoded_size += PB._encoded_size(x.weighted_dnlv, 7))
    !isempty(x.marginal_utility_by_holding) && (encoded_size += PB._encoded_size(x.marginal_utility_by_holding, 8))
    x.total_objective !== zero(Float64) && (encoded_size += PB._encoded_size(x.total_objective, 9))
    !isempty(x.marginal_scaled_objective_by_holding) && (encoded_size += PB._encoded_size(x.marginal_scaled_objective_by_holding, 10))
    return encoded_size
end

struct RequestStressTestDsPb
    ts::String
    underlying::String
    holdings::Dict{String,Common_pb.HoldingPb}
    market_data_snaps::Vector{Common_pb.MarketDataSnapByUnderlyingPb}
    params::Vector{RequestSSVICalibration_pb.SSVIParamsPb}
end
PB.default_values(::Type{RequestStressTestDsPb}) = (;ts = "", underlying = "", holdings = Dict{String,Common_pb.HoldingPb}(), market_data_snaps = Vector{Common_pb.MarketDataSnapByUnderlyingPb}(), params = Vector{RequestSSVICalibration_pb.SSVIParamsPb}())
PB.field_numbers(::Type{RequestStressTestDsPb}) = (;ts = 1, underlying = 2, holdings = 3, market_data_snaps = 4, params = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RequestStressTestDsPb}, _endpos::Int=0, _group::Bool=false)
    ts = ""
    underlying = ""
    holdings = Dict{String,Common_pb.HoldingPb}()
    market_data_snaps = PB.BufferedVector{Common_pb.MarketDataSnapByUnderlyingPb}()
    params = PB.BufferedVector{RequestSSVICalibration_pb.SSVIParamsPb}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ts = PB.decode(d, String)
        elseif field_number == 2
            underlying = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, holdings)
        elseif field_number == 4
            PB.decode!(d, market_data_snaps)
        elseif field_number == 5
            PB.decode!(d, params)
        else
            Base.skip(d, wire_type)
        end
    end
    return RequestStressTestDsPb(ts, underlying, holdings, market_data_snaps[], params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RequestStressTestDsPb)
    initpos = position(e.io)
    !isempty(x.ts) && PB.encode(e, 1, x.ts)
    !isempty(x.underlying) && PB.encode(e, 2, x.underlying)
    !isempty(x.holdings) && PB.encode(e, 3, x.holdings)
    !isempty(x.market_data_snaps) && PB.encode(e, 4, x.market_data_snaps)
    !isempty(x.params) && PB.encode(e, 5, x.params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RequestStressTestDsPb)
    encoded_size = 0
    !isempty(x.ts) && (encoded_size += PB._encoded_size(x.ts, 1))
    !isempty(x.underlying) && (encoded_size += PB._encoded_size(x.underlying, 2))
    !isempty(x.holdings) && (encoded_size += PB._encoded_size(x.holdings, 3))
    !isempty(x.market_data_snaps) && (encoded_size += PB._encoded_size(x.market_data_snaps, 4))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 5))
    return encoded_size
end
end # module
