# Autogenerated using ProtoBuf.jl v1.3.0
# original file: Websocket.proto (proto3 syntax)

module Websocket_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ActionPb, ChannelPb, MessagePb


@enumx ActionPb SUBSCRIBE=0 UNSUBSCRIBE=1

@enumx ChannelPb HB=0 TARGET_PORTFOLIO=1 ECHO=2 TERMINATE=3 STRESS_TEST_DS=4 CMD_FETCH_TARGET_PORTFOLIO=5 CMD_CANCEL_OID=6 KALMAN_INIT=7 CMD_CFG_OVERRIDE=8 REQUEST_SSVI_CALIBRATION=9 REQUEST_PF_RISK_SCENARIOS=10

struct MessagePb
    channel::ChannelPb.T
    id::String
    action::ActionPb.T
    payload::Vector{UInt8}
end
PB.default_values(::Type{MessagePb}) = (;channel = ChannelPb.HB, id = "", action = ActionPb.SUBSCRIBE, payload = UInt8[])
PB.field_numbers(::Type{MessagePb}) = (;channel = 1, id = 2, action = 3, payload = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MessagePb}, _endpos::Int=0, _group::Bool=false)
    channel = ChannelPb.HB
    id = ""
    action = ActionPb.SUBSCRIBE
    payload = UInt8[]
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            channel = PB.decode(d, ChannelPb.T)
        elseif field_number == 2
            id = PB.decode(d, String)
        elseif field_number == 3
            action = PB.decode(d, ActionPb.T)
        elseif field_number == 4
            payload = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return MessagePb(channel, id, action, payload)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MessagePb)
    initpos = position(e.io)
    x.channel != ChannelPb.HB && PB.encode(e, 1, x.channel)
    !isempty(x.id) && PB.encode(e, 2, x.id)
    x.action != ActionPb.SUBSCRIBE && PB.encode(e, 3, x.action)
    !isempty(x.payload) && PB.encode(e, 4, x.payload)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MessagePb)
    encoded_size = 0
    x.channel != ChannelPb.HB && (encoded_size += PB._encoded_size(x.channel, 1))
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 2))
    x.action != ActionPb.SUBSCRIBE && (encoded_size += PB._encoded_size(x.action, 3))
    !isempty(x.payload) && (encoded_size += PB._encoded_size(x.payload, 4))
    return encoded_size
end
end # module
